# This Workflow generates a changelog
name: Release - Generate changelog
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version for which a changelog should be generated. Should be in format 7.y.z'
        required: true
        default: ''
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Create changelog
      # wrapper for https://github.com/github-changelog-generator/github-changelog-generator
      uses: heinrichreimer/github-changelog-generator-action@v2.1.1
      with:
        token: ${{ secrets.CHE_BOT_GITHUB_TOKEN }}
        repo: eclipse/che 
        project: "Eclipse Che"
        dateFormat: "%Y-%m-%d"
        output: CHANGELOG-next.md
        verbose: false
        releaseBranch: master # TODO: change to main
        dueTag: ${{ github.event.inputs.version }} # all issues up to the current release tag
        filterByMilestone: false # this requires that we get good at setting milestone when something is actually DONE rather than when we think it'll be done
        pullRequests: false # only include issues, not PRs, since PRs span multiple repos and are too noisy to include
        issuesWoLabels: false # no labels? no logged change
        issues: true
        issueLineLabels: "ALL"
        compareLink: true
        unreleased: true # show unreleased, but closed items
        addSections: '{"sprint/current-sprint":{"prefix":"**Issues in Current Sprint:**","labels":["sprint/current-sprint"]}, "new&noteworthy":{"prefix":"**New and Noteworthy Issues:**","labels":["new&noteworthy"]}}'
        excludeTags: '' # comma,delimited,list,of,tags
        # includeLabels: ''
        excludeLabels: "kind/release"
        enhancementLabel: "Enhancements, Epics, and UX"
        enhancementLabels: "kind/enhancement,kind/epic,kind/ux"
        bugsLabel: "Bugs fixed"
        bugsLabels: "kind/bug"
